package persistencia.clasesHibernate;
// Generated 13-may-2017 17:19:02 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements Serializable {

	private static final long serialVersionUID = -1467650311214849101L;
	private Integer id;
	private String usuario;
	private String contrasenna;
	private String email;
	private String tipo;
	private Set<Asignatura> asignaturas = new HashSet<Asignatura>(0);
	private Set<Mensaje> mensajes = new HashSet<Mensaje>(0);

	public Cliente() {
	}

	public Cliente(String usuario, String contrasenna, String email, String tipo) {
		this.usuario = usuario;
		this.contrasenna = contrasenna;
		this.email = email;
		this.tipo = tipo;
	}

	public Cliente(String usuario, String contrasenna, String email, String tipo, Set<Asignatura> asignaturas,
			Set<Mensaje> mensajes) {
		this.usuario = usuario;
		this.contrasenna = contrasenna;
		this.email = email;
		this.tipo = tipo;
		this.asignaturas = asignaturas;
		this.mensajes = mensajes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getContrasenna() {
		return this.contrasenna;
	}

	public void setContrasenna(String contrasenna) {
		this.contrasenna = contrasenna;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getTipo() {
		return this.tipo;
	}

	public void setTipo(String tipo) {
		this.tipo = tipo;
	}

	public Set<Asignatura> getAsignaturas() {
		return this.asignaturas;
	}

	public void setAsignaturas(Set<Asignatura> asignaturas) {
		this.asignaturas = asignaturas;
	}

	public Set<Mensaje> getMensajes() {
		return this.mensajes;
	}

	public void setMensajes(Set<Mensaje> mensajes) {
		this.mensajes = mensajes;
	}

}
