package persistencia.clasesHibernate;
// Generated 13-may-2017 17:19:02 by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje implements Serializable {

	private static final long serialVersionUID = 4440077448756564416L;
	private Integer id;
	private byte[] mensaje;
	private Set<Cliente> clientes = new HashSet<Cliente>(0);

	public Mensaje() {
	}

	public Mensaje(byte[] mensaje, Set<Cliente> clientes) {
		this.mensaje = mensaje;
		this.clientes = clientes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public byte[] getMensaje() {
		return this.mensaje;
	}

	public void setMensaje(byte[] mensaje) {
		this.mensaje = mensaje;
	}

	public Set<Cliente> getClientes() {
		return this.clientes;
	}

	public void setClientes(Set<Cliente> clientes) {
		this.clientes = clientes;
	}

}
